# Generated by Django 4.2.4 on 2023-09-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_tasks_alter_employee_department_roles_employee_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='notes',
            field=models.FileField(upload_to='leave_request_files'),
        ),
    ]
