# Generated by Django 4.2.4 on 2023-09-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_customuser_options_remove_customuser_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='is_shift_record',
        ),
        migrations.AddField(
            model_name='timerecord',
            name='is_clock_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timerecord',
            name='record_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='clock_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
