# Generated by Django 4.2.4 on 2023-09-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_employee_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
