# Generated by Django 4.2.4 on 2023-09-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hourly_rate',
        ),
    ]
