# Generated by Django 4.2.1 on 2023-09-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_remove_employee_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timerecord',
            name='notes',
        ),
    ]
