# Generated by Django 4.2.4 on 2023-09-10 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0017_timerecord_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timerecord',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_time_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='clock_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='clock_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timerecord',
            name='is_clock_in',
            field=models.BooleanField(default=False),
        ),
    ]
