# Generated by Django 4.2.4 on 2023-09-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_employee_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='timerecord',
            name='is_clock_out',
            field=models.BooleanField(default=False),
        ),
    ]
