# Generated by Django 4.2.1 on 2023-08-30 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_leaverequest_paymentrecord_employee_hourly_rate_and_more'),
        ('Employee', '0002_remove_employee_email_remove_employee_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('routing_number', models.CharField(max_length=50)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Admin.employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='document',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employeetoken',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeetoken',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='reportinglog',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='reportinglog',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='reportinglog',
            name='token',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeToken',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='ReportingLog',
        ),
    ]
